apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-react-7b735
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/deploy-react-7b735.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: deploy-react-7b735
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
